version: "3"

services:
  postgres:
    image: postgres:14.13-alpine
    restart: always
    environment:
      POSTGRES_DB: "web"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql-14/data

  pgadmin:
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin-8
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin: